Update ru.yml
lorcalhost/BTB-manager-telegram pull request #198
Opened 2021-12-15 16:54 UTC by kelecheck

Minor edits

2021-12-15 19:40 UTC, DmytroLitvinov requested changes

2021-12-15 19:40 UTC, DmytroLitvinov commented on i18n/ru.yml
> +  donation: "*Если Вам нравятся мои работы, пожалуйста рассмотрите возможность поддержки проекта небольшим [пожертвованием](https://github.com/sponsors/lorcalhost). ❤*"
Слово `пожалуйста` должно быть выделено двумя запятыми, потому что это вводное слово.

2021-12-15 20:43 UTC, DmytroLitvinov approved these changes

2021-12-15 20:43 UTC, merged

2021-12-17 08:30 UTC, titulebolide commented
@all-contributors please add @kelecheck for translation