Bot stats
lorcalhost/BTB-manager-telegram pull request #213
Opened 2022-01-04 21:46 UTC by titulebolide

It is the follow up from #210 since @ullasbharadwaj deleted his repo

What's left to do:

- [ ] Use the table.tabularize tables instead of prettytable
- [ ] Take care that long coin list will not trigger Too long message errors
- [ ] Use translation files for bot_stats

2022-01-04 21:54 UTC, ullasbharadwaj commented
I am sorry, deleted wrong repo, I had a different fork from long ago and instead of deleting that, I deleted the latest one :-( I am sorry.

2022-01-04 21:59 UTC, titulebolide commented
No worries!

2022-01-04 22:04 UTC, titulebolide commented
@all-contributors please add @ullasbharadwaj for ideas,code

2022-01-04 22:04 UTC, titulebolide commented
@all-contributors please add @ullasbharadwaj for ideas, code

2022-01-05 04:17 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +        cur.execute("select symbol from coins where enabled=1")
```suggestion
        cur.execute("SELECT symbol FROM coins WHERE enabled=1")
```

2022-01-05 04:27 UTC, DmytroLitvinov requested changes

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +            "SELECT alt_coin_id FROM trade_history where id=1 and state='COMPLETE' order by id asc limit 1"
```suggestion
            "SELECT alt_coin_id FROM trade_history WHERE id=1 and state='COMPLETE' ORDER BY id ASC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                "SELECT alt_coin_id FROM trade_history where id='{}' and state='COMPLETE' order by id asc limit 1".format(
```suggestion
                "SELECT alt_coin_id FROM trade_history WHERE id='{}' and state='COMPLETE' ORDER BY id ASC LIMIT 1".format(
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                        "select alt_trade_amount from trade_history where alt_coin_id='{}' and state='COMPLETE' order by id asc limit 1".format(
```suggestion
                        "SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id='{}' and state='COMPLETE' ORDER BY id ASC LIMIT 1".format(
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                        "select crypto_trade_amount from trade_history where alt_coin_id='{}' and state='COMPLETE' order by id asc limit 1".format(
```suggestion
                        "SELECT crypto_trade_amount FROM trade_history WHERE alt_coin_id='{}' and state='COMPLETE' ORDER BY id ASC LIMIT 1".format(
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +            "select alt_coin_id from trade_history where selling=0 and state='COMPLETE' order by id desc limit 1"
```suggestion
            "SELECT alt_coin_id FROM trade_history WHERE selling=0 and state='COMPLETE' ORDER BY id DESC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +            "select alt_trade_amount from trade_history where selling=0 and state='COMPLETE' order by id desc limit 1"
```suggestion
            "SELECT alt_trade_amount FROM trade_history WHERE selling=0 and state='COMPLETE' ORDER BY id DESC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +            "select current_coin_price from scout_history order by rowid desc limit 1"
```suggestion
            "SELECT current_coin_price FROM scout_history ORDER BY rowid DESC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                "select id from pairs where from_coin_id='{}' and to_coin_id='{}'".format(
```suggestion
                "SELECT id FROM pairs WHERE from_coin_id='{}' and to_coin_id='{}'".format(
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                "select other_coin_price from scout_history where pair_id='{}' order by id desc limit 1".format(
```suggestion
                "SELECT other_coin_price FROM scout_history WHERE pair_id='{}' ORDER BY id DESC LIMIT 1".format(
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                "select current_coin_price from scout_history order by id desc limit 1"
```suggestion
                "SELECT current_coin_price FROM scout_history ORDER BY id DESC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                f"select count(*) from trade_history where alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE'"
```suggestion
                f"SELECT COUNT(*) FROM trade_history WHERE alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE'"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                    f"select datetime from trade_history where alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' order by id asc limit 1"
```suggestion
                    f"SELECT datetime FROM trade_history WHERE alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' ORDER BY id ASC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                    f"select alt_trade_amount from trade_history where alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' order by id asc limit 1"
```suggestion
                    f"SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' ORDER BY id ASC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                    f"select alt_trade_amount from trade_history where alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' order by id desc limit 1"
```suggestion
                    f"SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id='{coin[0]}' and selling=0 and state='COMPLETE' ORDER BY id DESC LIMIT 1"
```

2022-01-05 04:27 UTC, DmytroLitvinov commented on btb_manager_telegram/buttons.py
> +                "select other_coin_price from scout_history where pair_id='{}' order by id desc limit 1".format(
```suggestion
                "SELECT other_coin_price FROM scout_history WHERE pair_id='{}' ORDER BY id DESC LIMIT 1".format(
```

2022-01-05 09:27 UTC, titulebolide commented
This bug as been pointed out:
Traceback (most recent call last):
  File "/home/ubuntu/binance-trade-bot/Binance1/binance-trade-bot/custom_scripts/bot_stats.py", line 20, in <module>
    initialCoinID = db.fetchall()[0][0]
IndexError: list index out of range

2022-01-05 12:07 UTC, ullasbharadwaj commented on btb_manager_telegram/buttons.py
> +                        float(grow),
2 decimals is sufficient for growth percentage ? Looks neat.

2022-01-05 21:59 UTC, ullasbharadwaj commented
You mean in profit calculation? I assumed, it makes sense to see the profit in USD as the current holding to the HODL holding which means profit percentage in terms of Coin/USD is the same. But if you see the profit in Fiat as the change between USDValueAtBotStart and CurrentUSDValue, then we will have different profit percentages.

2022-01-06 10:49 UTC, titulebolide commented
Ohhh that's why! It was unclear, I thought the profit was relative to the start of the bot. IMO it is clearer to show the actual profit in USD (thus relative to the start) and the actual profit in the start coin (which then is equivalent to the profit relative to the HODL)

2022-01-06 11:22 UTC, ullasbharadwaj commented
My bad, it was not clear. We can modify as you said, then we have 2 perspectives of visualising the profit. 👍

2022-01-06 13:49 UTC, titulebolide commented
Here it is! 
`Profit       : -3.96% USD / +5.26% QTUM`

2022-01-06 13:49 UTC, titulebolide commented
If you are happy with how it is, it is ready to be merged

2022-01-06 14:10 UTC, ullasbharadwaj commented
Yes perfect. Thanks for great work.

2022-01-06 14:20 UTC, merged